---
- name: "Download Kibana's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-x86_64.rpm"
    dest: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
    mode: 0740
  register: download_kibana
  until: download_kibana is succeeded
